# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish (x64)
      run: dotnet publish ./WID/WID.csproj -c Release -r win-x64 --self-contained true -o out/x64
    - name: Publish (arm64)
      run: dotnet publish ./WID/WID.csproj -c Release -r win-arm64 --self-contained true -o out/arm64
    - name: Test (x64)
      run: dotnet test --no-build --verbosity normal --arch x64
    - name: Test (arm64)
      run: dotnet test --no-build --verbosity normal --arch arm64