# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        arch: ["x64, arm64"]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build (${{ matrix.arch }})
      run: dotnet build --no-restore -r win-${{ matrix.arch }} -c Release
    - name: Test (${{ matrix.arch }})
      run: dotnet test --no-build --verbosity normal -r win-${{ matrix.arch }}
